from .model import (
    App,
    Config,
    CydiaRepoDebFile,
    GithubReleasesDebFile,
    GithubRepo,
    Tweak,
)

config = Config(
    local_username="gx8z",
    this_repo=GithubRepo("ZMyApps/core"),
    files_repo=GithubRepo("ZMyApps/files"),
    files_repo_json_tag="json",
    build_archive_repo=GithubRepo("ZMyApps/build-archive"),
    ipa_archive_repo=GithubRepo("ZMyApps/ipa-archive"),
    apps=[
        App(
            name="Apollo",
            bundle_identifier="com.christianselig.Apollo",
            tweaks=[
                Tweak(
                    name="ApolloICA",
                    deb_files=[
                        GithubReleasesDebFile(
                            repo=GithubRepo("JeffreyCA/Apollo-ImprovedCustomApi"),
                            endswith="rootless.deb",
                            use_version=True,
                        )
                    ],
                )
            ],
        ),
        App(
            name="Facebook",
            bundle_identifier="com.facebook.Facebook",
            tweaks=[
                Tweak(
                    name="FacebookGlow",
                    deb_files=[
                        GithubReleasesDebFile(
                            repo=GithubRepo("dayanch96/Glow"),
                            endswith="arm64.deb",
                            use_version=True,
                        )
                    ],
                )
            ],
        ),
        App(
            name="Infuse",
            bundle_identifier="com.firecore.infuse",
            tweaks=[
                Tweak(
                    name="InfusePlus",
                    deb_files=[
                        GithubReleasesDebFile(
                            repo=GithubRepo("dayanch96/InfusePlus"),
                            endswith="arm64.deb",
                            use_version=True,
                        )
                    ],
                )
            ],
        ),
        App(
            name="Instagram",
            bundle_identifier="com.burbn.instagram",
            tweaks=[
                Tweak(
                    name="SCInsta",
                    deb_files=[
                        GithubReleasesDebFile(
                            repo=GithubRepo("SoCuul/SCInsta"),
                            endswith="rootless.deb",
                            use_version=True,
                        )
                    ],
                ),
                Tweak(
                    name="RyukGram",
                    deb_files=[
                        GithubReleasesDebFile(
                            repo=GithubRepo("faroukbmiled/RyukGram"),
                            endswith="rootless.deb",
                            use_version=True,
                        )
                    ],
                ),
            ],
        ),
        App(name="TikTok", bundle_identifier="com.zhiliaoapp.musically"),
        # App(name="TikTokGlobal", bundle_identifier="com.ss.iphone.ugc.Ame"),
        App(
            name="X",
            bundle_identifier="com.atebits.Tweetie2",
            tweaks=[
                Tweak(
                    name="BHTwitter",
                    deb_files=[
                        GithubReleasesDebFile(
                            repo=GithubRepo("BandarHL/BHTwitter"),
                            endswith="arm64.deb",
                            use_version=True,
                        )
                    ],
                )
            ],
        ),
        App(
            name="YouTube",
            bundle_identifier="com.google.ios.youtube",
            tweaks=[
                Tweak(
                    name="YouMod",
                    deb_files=[
                        GithubReleasesDebFile(
                            repo=GithubRepo("Tonwalter888/YouMod"),
                            endswith="arm64.deb",
                            use_version=True,
                        ),
                        CydiaRepoDebFile(
                            repo="https://poomsmart.github.io/repo",
                            package="com.ps.ytvideooverlay",
                            architecture="iphoneos-arm64",
                        ),
                        CydiaRepoDebFile(
                            repo="https://poomsmart.github.io/repo",
                            package="com.ps.youpip",
                            architecture="iphoneos-arm64",
                        ),
                    ],
                ),
                Tweak(
                    name="ZMyYouTube",
                    deb_files=[
                        CydiaRepoDebFile(
                            repo="https://poomsmart.github.io/repo",
                            package="com.ps.ytabgoodies",
                            architecture="iphoneos-arm64",
                        ),
                        CydiaRepoDebFile(
                            repo="https://poomsmart.github.io/repo",
                            package="com.ps.ytx",
                            architecture="iphoneos-arm64",
                        ),
                        CydiaRepoDebFile(
                            repo="https://poomsmart.github.io/repo",
                            package="com.ps.ytvideooverlay",
                            architecture="iphoneos-arm64",
                        ),
                        CydiaRepoDebFile(
                            repo="https://poomsmart.github.io/repo",
                            package="com.ps.youpip",
                            architecture="iphoneos-arm64",
                        ),
                        GithubReleasesDebFile(
                            repo=GithubRepo("hbang/Alderis"),
                            tag="1.2.3",
                            endswith="arm64.deb",
                        ),
                        CydiaRepoDebFile(
                            repo="https://repo.icrazeios.com",
                            package="com.galacticdev.isponsorblock",
                            architecture="iphoneos-arm64",
                        ),
                    ],
                ),
            ],
        ),
        App(
            name="YouTubeMusic",
            bundle_identifier="com.google.ios.youtubemusic",
            tweaks=[
                Tweak(
                    name="YTMusicUltimate",
                    deb_files=[
                        GithubReleasesDebFile(
                            repo=GithubRepo("dayanch96/YTMusicUltimate"),
                            endswith="arm64.deb",
                            use_version=True,
                        )
                    ],
                )
            ],
        ),
    ],
)
